from typing import Optional, List, Dict, Any, Literal
from pydantic import BaseModel, Field
ProviderRuntimeType=Literal['mock','openai_compatible','anthropic_compatible','custom_http','local','disabled']
ProviderConnectionStatus=Literal['unknown','not_configured','configured','testing','connected','failed','disabled','blocked']
ProviderAuthType=Literal['none','bearer_token','api_key_header','custom_header']
class ProviderPreset(BaseModel):
    presetId: str; displayName: str; runtimeType: ProviderRuntimeType='openai_compatible'; defaultBaseUrl: str=''; defaultModel: Optional[str]=None; authType: ProviderAuthType='bearer_token'; authHeaderName: str='Authorization'; requestFormat: str='openai_chat_completions'; responseFormat: str='openai_chat_completions'; supportsModelDiscovery: bool=False; supportsStreaming: bool=False; notes: List[str]=Field(default_factory=list); metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderRuntimeConfig(BaseModel):
    providerId: str; presetId: Optional[str]=None; runtimeType: ProviderRuntimeType='mock'; baseUrl: Optional[str]=None; model: Optional[str]=None; authType: ProviderAuthType='none'; secretRef: Optional[str]=None; secretStatus: str='not_required'; liveCallsAllowed: bool=False; enabled: bool=False; timeoutSeconds: int=30; maxInputChars: int=12000; maxOutputChars: int=8000; maxTokens: Optional[int]=1000; temperature: Optional[float]=0.2; extraHeaders: Dict[str,str]=Field(default_factory=dict); metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderConnectionTestRequest(BaseModel): providerId: str; mode: Literal['metadata_only','health','live_minimal']='metadata_only'; metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderConnectionTestResult(BaseModel): testId: str; providerId: str; status: ProviderConnectionStatus='unknown'; mode: str='metadata_only'; connected: bool=False; message: str=''; latencyMs: Optional[int]=None; model: Optional[str]=None; baseUrl: Optional[str]=None; warnings: List[str]=Field(default_factory=list); errors: List[str]=Field(default_factory=list); metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderLiveCallRequest(BaseModel): providerId: str; input: str; systemPrompt: Optional[str]=None; taskType: Optional[str]=None; metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderLiveCallResult(BaseModel): callId: str; providerId: str; status: Literal['completed','blocked','failed']='blocked'; outputText: Optional[str]=None; normalizedOutput: Optional[Dict[str,Any]]=None; latencyMs: Optional[int]=None; usage: Dict[str,Any]=Field(default_factory=dict); warnings: List[str]=Field(default_factory=list); errors: List[str]=Field(default_factory=list); metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderUsageRecord(BaseModel): usageId: str; providerId: str; createdAt: str=''; requestType: str=''; inputChars: int=0; outputChars: int=0; estimatedTokens: int=0; latencyMs: Optional[int]=None; status: str=''; metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderUsageSummary(BaseModel): providerId: str; callsTotal: int=0; callsSucceeded: int=0; callsFailed: int=0; callsBlocked: int=0; inputCharsTotal: int=0; outputCharsTotal: int=0; estimatedTokensTotal: int=0; lastCallAt: Optional[str]=None; metadata: Dict[str,Any]=Field(default_factory=dict)
class ProviderDiagnostics(BaseModel): providerId: str; status: ProviderConnectionStatus='unknown'; configured: bool=False; enabled: bool=False; liveCallsAllowed: bool=False; hasSecretRef: bool=False; secretStatus: str='not_required'; baseUrl: Optional[str]=None; model: Optional[str]=None; lastTestAt: Optional[str]=None; lastError: Optional[str]=None; usage: Optional[ProviderUsageSummary]=None; warnings: List[str]=Field(default_factory=list); metadata: Dict[str,Any]=Field(default_factory=dict)
class ModelDiscoveryRequest(BaseModel): providerId: str; metadata: Dict[str,Any]=Field(default_factory=dict)
class ModelDiscoveryResult(BaseModel): providerId: str; supported: bool=False; status: str='blocked'; models: List[str]=Field(default_factory=list); warnings: List[str]=Field(default_factory=list); errors: List[str]=Field(default_factory=list); metadata: Dict[str,Any]=Field(default_factory=dict)
class CreateProviderFromPresetRequest(BaseModel): providerId: str; presetId: str; displayName: Optional[str]=None; metadata: Dict[str,Any]=Field(default_factory=dict)
class BindProviderSecretRequest(BaseModel): secretRef: str; metadata: Dict[str,Any]=Field(default_factory=dict)
class CreateProviderSecretRequest(BaseModel): name: str; value: str; kind: str='api_key'; metadata: Dict[str,Any]=Field(default_factory=dict)
