'use strict';
// Exact static asset bytes; native guards/storage/locks, public inert diagnostic controls.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium,webkit}=require('playwright-core');
const [sourcePath,output]=process.argv.slice(2),source=fs.readFileSync(sourcePath),bundle=JSON.parse(source),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const assets=Object.fromEntries(Object.entries(bundle.assets).map(([k,v])=>[k,Buffer.from(v,'base64')]));
const origin='https://device-check.invalid',base='/preview/device-check/';
const csp="default-src 'self'; script-src 'self' https://telegram.org; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'self' https://web.telegram.org https://*.telegram.org";
const report={sourceSha256:hash(source),runnerSha256:hash(fs.readFileSync(__filename)),assetSha256:Object.fromEntries(Object.entries(assets).map(([k,v])=>[k,hash(v)])),engine:bundle.engine,playwrightVersion:require('playwright-core/package.json').version,screenshots:bundle.engine==='webkit'?'omitted: Playwright WebKit screenshot sync injects inline body{} stylesheet; separate exact-asset visual evidence retained':'native',checks:[],pageErrors:[],unexpectedRequests:[],consoleErrors:[]};
fs.mkdirSync(output,{recursive:true});
async function main(){assert.notEqual(process.getuid(),0);const browser=await(bundle.engine==='webkit'?webkit.launch({headless:true}):chromium.launch({executablePath:'/opt/google/chrome/chrome',chromiumSandbox:true,headless:true}));report.browserVersion=browser.version();let page;
try {for(const width of [320,390]){
 const context=await browser.newContext({viewport:{width,height:844},serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('oe.wallet-attempt.shared.v1','PRODUCTION-SHARED-SENTINEL');sessionStorage.setItem('oe.wallet-attempt.v1','PRODUCTION-SESSION-SENTINEL');});
 await context.route('**/*',async route=>{const u=new URL(route.request().url());let name=u.pathname.slice(base.length)||'index.html';if(u.origin!==origin||!u.pathname.startsWith(base)||route.request().method()!=='GET'||!assets[name]){report.unexpectedRequests.push({method:route.request().method(),path:u.pathname});return route.abort();}return route.fulfill({body:assets[name],contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':'application/json',headers:{'Content-Security-Policy':csp}});});
 async function newPage(){const p=await context.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({text:m.text(),location:m.location(),phase:report.phase});});await p.goto(origin+base,{waitUntil:'load'});return p;}
 page=await newPage();
 async function snapshot(p=page){return JSON.parse(await p.locator('#device-report').inputValue());}
 async function sentinel(p=page){assert.deepEqual(await p.evaluate(()=>({shared:localStorage.getItem('oe.wallet-attempt.shared.v1'),session:sessionStorage.getItem('oe.wallet-attempt.v1')})),{shared:'PRODUCTION-SHARED-SENTINEL',session:'PRODUCTION-SESSION-SENTINEL'});}
 function pass(name){report.checks.push({width,case:name,result:'PASS'});}
 async function open(p,kind='transfer'){await p.locator('#device-'+kind).click();await p.locator('#exchange-review').waitFor({state:'visible'});assert.equal(await p.locator('#exchange-review-ack').isChecked(),false);assert.equal(await p.locator('#exchange-review-confirm').isDisabled(),true);await p.locator('#exchange-review-ack').check();}
 async function confirm(p=page,kind='transfer'){await open(p,kind);await p.locator('#exchange-review-confirm').click();}

 const manifest=JSON.parse(assets['manifest.json']);
 const initial=await snapshot();assert.equal(initial.environment.userChoice,'unknown');assert.equal(initial.environment.verified,false);assert.equal(initial.realWalletConnected,false);assert.equal(initial.realTransferPerformed,false);assert.deepEqual(initial.build,manifest.build);assert.equal(initial.counters.sdkCalls,0);
 for(const [name,digest] of Object.entries(manifest.artifacts))assert.equal(hash(assets[name]),digest);
 await page.locator('#device-environment').selectOption('telegram-miniapp-ios');assert.equal((await snapshot()).environment.verified,false);assert.equal((await snapshot()).environment.userChoice,'telegram-miniapp-ios');
 assert.equal(await page.locator('script[src*="telegram"],script[src*="tonconnect"]').count(),0);pass('build provenance and user-selected environment never claim physical-device verification');
 await page.evaluate(()=>{navigator.locks.request('oe.wallet-handoff.v1',async()=>{window.__productionLockHeld=true;await new Promise(r=>window.__releaseProductionLock=r);});});await page.waitForFunction(()=>window.__productionLockHeld===true);
 await open(page);report.phase='review screenshot';if(bundle.engine==='chromium')await page.screenshot({path:path.join(output,`${width}-review.png`),caret:'initial'});report.phase='actions';await page.locator('#exchange-review-cancel').click();assert.equal((await snapshot()).counters.sdkCalls,0);pass('review cancel never invokes inert SDK');
 await confirm();await page.waitForFunction(()=>JSON.parse(document.getElementById('device-report').value).counters.sdkCalls===1);assert.equal((await snapshot()).pending,true);
 await page.locator('#device-payment').click();assert.equal((await snapshot()).counters.sdkCalls,1);assert.equal(await page.locator('#wallet-attempt-remove').isDisabled(),true);assert.ok((await page.evaluate(()=>navigator.locks.query())).held.some(l=>l.name==='oe.wallet-handoff.v1'));await sentinel();
 await page.locator('#device-resolve').click();await page.waitForFunction(()=>JSON.parse(document.getElementById('device-report').value).lastOutcome==='synthetic-resolved');assert.equal((await snapshot()).attemptPresent,true);
 await page.locator('#device-reload').click();await page.waitForLoadState('load');await page.waitForFunction(()=>document.getElementById('device-report').value.length>0);assert.equal((await snapshot()).attemptPresent,true);assert.equal((await snapshot()).counters.sdkCalls,0);assert.equal((await snapshot()).pending,false);
 await page.locator('#device-transfer').click();assert.equal((await snapshot()).counters.sdkCalls,0);await page.locator('#wallet-attempt-notice').scrollIntoViewIfNeeded();report.phase='notice screenshot';if(bundle.engine==='chromium')await page.screenshot({path:path.join(output,`${width}-reload-notice.png`),caret:'initial'});report.phase='actions';
 async function clear(p=page){assert.equal(await p.locator('#wallet-attempt-remove').isDisabled(),true);await p.locator('#wallet-attempt-ack').check();await p.locator('#wallet-attempt-remove').click();await p.waitForFunction(()=>!JSON.parse(document.getElementById('device-report').value).attemptPresent);}
 await clear();assert.equal((await snapshot()).counters.sdkCalls,0);pass('pending blocks repeat under isolated native lock; accepted response and reload retain evidence; explicit clear never signs');
 await confirm(page,'payment');await page.waitForFunction(()=>JSON.parse(document.getElementById('device-report').value).counters.sdkCalls===1);await page.locator('#device-reject').click();await page.waitForFunction(()=>JSON.parse(document.getElementById('device-report').value).lastOutcome==='synthetic-rejected-unknown');assert.equal((await snapshot()).attemptPresent,true);await clear();assert.equal((await snapshot()).counters.sdkCalls,1);pass('payment unknown outcome retains reminder until explicit check');
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied');}}});});await page.locator('#device-report-copy').click();await page.waitForFunction(()=>document.getElementById('device-copy-status').textContent.includes('вручную'));assert.equal(await page.locator('#device-report').getAttribute('readonly'),'');assert.ok((await page.locator('#device-report').inputValue()).includes('manual-observation-only'));
 await page.evaluate(()=>{navigator.clipboard.writeText=async text=>{window.__copied=text;};});await page.locator('#device-report-copy').click();await page.waitForFunction(()=>document.getElementById('device-copy-status').textContent.includes('скопирован'));const copied=await page.evaluate(()=>window.__copied);assert.equal(copied,await page.locator('#device-report').inputValue());assert.ok(!copied.includes('PRODUCTION-'));assert.ok(!copied.includes('0:'+ 'b'.repeat(64)));assert.equal(JSON.parse(copied).environment.verified,false);pass('clipboard denied keeps manual report fallback; successful copy contains minimal truthful report');
 const other=await newPage();await open(page);await open(other,'payment');const beforeA=(await snapshot()).counters.sdkCalls;await Promise.all([page.locator('#exchange-review-confirm').click(),other.locator('#exchange-review-confirm').click()]);await page.waitForFunction(()=>!!localStorage.getItem('oe.device-check.wallet-attempt.shared.v1'));await Promise.race([page.waitForFunction(n=>JSON.parse(document.getElementById('device-report').value).counters.sdkCalls>n,beforeA),other.waitForFunction(()=>JSON.parse(document.getElementById('device-report').value).counters.sdkCalls===1)]);
 const callsA=(await snapshot()).counters.sdkCalls-beforeA,callsB=(await snapshot(other)).counters.sdkCalls;assert.equal(callsA+callsB,1);const winner=callsA?page:other,loser=callsA?other:page;await loser.locator('#wallet-attempt-notice').waitFor({state:'visible'});await loser.locator('#wallet-attempt-ack').check();await loser.locator('#wallet-attempt-remove').click();assert.equal((await snapshot(loser)).attemptPresent,true);await sentinel(loser);await sentinel(winner);
 await winner.locator('#device-reject').click();await winner.waitForFunction(()=>!JSON.parse(document.getElementById('device-report').value).pending);await clear(winner);pass('two actual pages permit one pending inert call and deny competing reconciliation');
 await other.close();await page.reload({waitUntil:'load'});await page.evaluate(()=>Object.defineProperty(navigator,'locks',{configurable:true,value:undefined}));await page.locator('#device-transfer').click();assert.equal((await snapshot()).counters.sdkCalls,0);assert.equal((await snapshot()).storageOrCoordinationFault,true);await sentinel();pass('unsupported coordination blocks diagnostic and never touches production keys');

 await sentinel();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);pass('static assets load under production CSP and production storage sentinels remain intact');
 await context.close();
}
assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.unexpectedRequests,[]);assert.deepEqual(report.consoleErrors,[]);report.result='PASS';
}catch(e){report.result='FAIL';report.error=e.stack;process.exitCode=1;if(page&&!page.isClosed())await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});}
finally{await browser.close();fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({result:report.result,cases:report.checks.length,error:report.error}));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
