MODULE_NAME = "Lumi"
VERSION = "1.7.0"
BUILD_NAME = "CONTROLLED_REAL_APPLY_BACKUP_ROLLBACK_GATE_FOUNDATION"
BUILD_STAGE = "controlled_real_apply_backup_rollback_gate_foundation"
API_VERSION = "1.7.0"

CAPABILITIES = [
    "local_persistence",
    "runtime_profiles",
    "storage_backend",
    "sqlite_storage_adapter",
    "json_snapshot_export",
    "json_snapshot_import",
    "startup_recovery",
    "redacted_state_persistence",
    "profile_manager",
    "storage_status",
    "storage_health",
    "data_retention_policy",
    "safe_reset_profile",
    "storage_ui_panel",
    "export_import_ui",
    "persistence_audit",
    "production_hardening_foundation",
    "startup_recovery_audit",
    "no_raw_secret_persistence",
    "local_auth", "protected_runtime_mode", "unlock_session", "access_token_auth",
    "admin_password_setup", "password_hashing", "security_status", "security_audit",
    "encryption_at_rest_foundation", "secret_vault", "secret_references",
    "masked_secret_display", "secret_create_update_delete", "vault_export_block",
    "vault_persistence", "protected_api_middleware", "ui_unlock_screen",
    "ui_security_panel", "ui_secret_vault_panel", "no_raw_secret_export",
    "safe_provider_key_storage", "security_hardening_foundation",

    "runtime_health",
    "version_metadata",
    "provider_registry",
    "adapter_interface",
    "mock_provider",
    "basic_resolve",
    "structured_decision",
    "audit_foundation",
    "secret_redaction",
    "fail_closed_errors",
    "capability_profiles",
    "role_registry",
    "role_assignment",
    "task_classification",
    "task_requirements",
    "provider_routing",
    "route_plan",
    "multi_provider_mock_routing",
    "routing_audit",
    "normalized_output",
    "output_validation_pipeline",
    "schema_validation",
    "empty_answer_detection",
    "malformed_output_detection",
    "confidence_validation",
    "suggested_status_validation",
    "risk_flag_validation",
    "evidence_requirement_check",
    "unsafe_wording_detection",
    "provider_output_scoring",
    "rejected_output_handling",
    "validation_audit",
    "conflict_detection",
    "disagreement_score",
    "provider_decision_signals",
    "deterministic_resolution",
    "resolution_priority_rules",
    "conflict_audit",
    "conflict_api",
    "policy_engine",
    "runtime_policies",
    "host_limits",
    "action_registry",
    "action_gateway",
    "action_proposals",
    "approval_prompts",
    "action_policy_check",
    "action_risk_levels",
    "action_dry_run_contract",
    "blocked_action_reasoning",
    "policy_audit",
    "approval_audit",
    "fail_closed_action_gateway",
    "decision_history",
    "decision_lookup",
    "decision_filtering",
    "decision_explainability",
    "human_readable_explanations",
    "technical_explanations",
    "decision_timeline",
    "audit_timeline",
    "dialog_sessions",
    "dialog_messages",
    "chat_command_gateway",
    "dialog_to_task_request",
    "dialog_response_summary",
    "approval_prompt_in_dialog",
    "session_decision_linking",
    "explainability_audit",
    "dialog_audit",
    "stable_rest_integration_contract",
    "host_app_registry",
    "host_app_manifest",
    "integration_handshake",
    "local_sidecar_mode",
    "connector_contract",
    "event_input_contract",
    "decision_callback_contract",
    "python_sdk_client",
    "javascript_sdk_client",
    "sdk_quickstart_examples",
    "host_app_examples",
    "dialog_sdk_support",
    "approval_sdk_support",
    "integration_audit",
    "easy_embed_foundation",

    "host_project_registry",
    "project_manifest",
    "project_inventory",
    "read_only_project_scan",
    "file_snapshot_ingestion",
    "static_project_inspection",
    "issue_detection",
    "improvement_candidates",
    "improvement_plan",
    "patch_plan_preview",
    "project_scan_audit",
    "improvement_history",
    "dialog_project_scan_support",
    "action_gateway_improvement_integration",
    "no_write_scanner_mode",
    "safe_project_analysis_foundation",
    "patch_planner",
    "patch_proposals",
    "diff_preview",
    "safe_diff_generation",
    "test_plan_preview",
    "test_runner_dry_run_contract",
    "rollback_metadata",
    "controlled_apply_preparation",
    "patch_action_gateway_integration",
    "patch_approval_prompt",
    "dialog_patch_preview_support",
    "integration_patch_preview_event",
    "no_write_patch_mode",
    "no_execute_test_mode",
    "patch_preview_audit",
    "rollback_audit",
    "controlled_sandbox_workspace",
    "sandbox_workspace_from_snapshots",
    "sandbox_patch_preview_apply",
    "sandbox_test_execution",
    "safe_command_allowlist",
    "command_execution_guard",
    "test_execution_audit",
    "sandbox_result_capture",
    "apply_preparation_package",
    "approval_gated_apply_preparation",
    "apply_package_action_gateway_integration",
    "rollback_metadata_in_apply_package",
    "dialog_sandbox_test_support",
    "dialog_apply_preparation_support",
    "integration_sandbox_test_event",
    "integration_apply_preparation_event",
    "no_host_write_mode",
    "no_network_execution_mode",
    "no_git_execution_mode",
    "local_ui_dashboard",
    "static_dashboard_assets",
    "dialog_window_foundation",
    "runtime_status_panel",
    "decision_history_panel",
    "explainability_panel",
    "approval_prompt_panel",
    "integration_wizard",
    "host_app_wizard",
    "project_manifest_wizard",
    "project_snapshot_upload_form",
    "project_scanner_panel",
    "patch_planner_panel",
    "sandbox_test_panel",
    "apply_preparation_review_panel",
    "safety_labels",
    "ui_audit",
    "no_frontend_build_required",

    "real_provider_runtime", "provider_connection_wizard", "provider_presets", "openai_compatible_adapter", "provider_secret_ref", "provider_live_call_gate", "safe_external_provider_call", "provider_connection_test", "provider_usage_tracking", "provider_diagnostics", "live_calls_disabled_by_default",
    "local_desktop_launcher", "windows_one_click_start", "browser_fallback_launch", "startup_diagnostics", "first_run_wizard", "local_runtime_logs", "local_app_folder_layout", "release_bundle_foundation", "launcher_health_check", "launcher_port_check", "launcher_readme",
    "ru_en_localization", "ru_first_dashboard", "en_secondary_dashboard", "language_setting", "language_switcher", "translation_dictionaries", "localized_safety_labels", "localized_dialog_commands", "localized_dialog_responses", "localized_ui_panels", "localized_docs_foundation", "multilingual_dialog_foundation", "api_codes_remain_english",
]