-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after 035-038.
GRANT SELECT(id,session_token,order_id,amount,provider,status,provider_invoice_id,created_at) ON public.payment_sessions TO obsidian_exchange_bot_owner;
GRANT SELECT(id,order_id,idempotency_key,state,source,requested_by,rub_amount,crypto_amount,currency,network,destination,attempts,txid,error_code,created_at,claimed_at,finished_at,updated_at) ON public.payout_intents TO obsidian_exchange_bot_owner;
GRANT SELECT(id,user_id,idempotency_key,state,crypto_amount,currency,network,destination,attempts,txid,error_code,created_at,claimed_at,finished_at,updated_at) ON public.referral_payout_intents TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b2_payment_latest(a_order_id bigint) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 THEN RAISE EXCEPTION 'invalid_order'; END IF; RETURN (SELECT jsonb_build_object('session_token',p.session_token,'status',p.status) FROM public.payment_sessions p WHERE p.order_id=a_order_id ORDER BY p.id DESC LIMIT 1); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payment_recent(a_order_id bigint,a_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 OR a_limit<1 OR a_limit>100 THEN RAISE EXCEPTION 'invalid_recent'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.id DESC) FROM (SELECT p.id,p.provider,p.provider_invoice_id,p.amount,p.status,p.created_at FROM public.payment_sessions p WHERE p.order_id=a_order_id ORDER BY p.id DESC LIMIT a_limit) q),'[]'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payment_provider_invoice(a_order_id bigint,a_provider text,a_prefix boolean) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN a_provider=trim(a_provider); IF a_order_id<=0 OR a_provider='' OR length(a_provider)>64 OR a_prefix IS NULL THEN RAISE EXCEPTION 'invalid_provider_lookup'; END IF; RETURN (SELECT jsonb_build_object('provider_invoice_id',p.provider_invoice_id,'provider',p.provider) FROM public.payment_sessions p WHERE p.order_id=a_order_id AND ((NOT a_prefix AND p.provider=a_provider) OR (a_prefix AND p.provider LIKE a_provider||'%')) AND p.provider_invoice_id IS NOT NULL ORDER BY p.created_at DESC,p.id DESC LIMIT 1); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payout_order(a_order_id bigint) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 THEN RAISE EXCEPTION 'invalid_order'; END IF; RETURN (SELECT to_jsonb(p) FROM public.payout_intents p WHERE p.order_id=a_order_id); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payout_order_exists(a_order_id bigint) RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 THEN RAISE EXCEPTION 'invalid_order'; END IF; RETURN EXISTS(SELECT 1 FROM public.payout_intents p WHERE p.order_id=a_order_id); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payout_referral(a_intent_id bigint) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_intent_id<=0 THEN RAISE EXCEPTION 'invalid_intent'; END IF; RETURN (SELECT to_jsonb(p) FROM public.referral_payout_intents p WHERE p.id=a_intent_id); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_payout_review(p_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'invalid_limit'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at,q.id) FROM (SELECT p.id,p.order_id,p.state,p.currency,p.network,p.crypto_amount,p.destination,p.txid,p.error_code,p.claimed_at,p.updated_at,o.status AS order_status FROM public.payout_intents p JOIN public.orders o ON o.order_id=p.order_id WHERE p.state IN('processing','review') ORDER BY p.updated_at,p.id LIMIT p_limit) q),'[]'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_referral_payout_review(p_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'invalid_limit'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at,q.id) FROM (SELECT p.id,p.user_id,p.state,p.currency,p.network,p.crypto_amount,p.destination,p.txid,p.error_code,p.claimed_at,p.updated_at FROM public.referral_payout_intents p WHERE p.state IN('processing','review') ORDER BY p.updated_at,p.id LIMIT p_limit) q),'[]'::jsonb); END $$;

ALTER FUNCTION public.bot_b2_payment_latest(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payment_recent(bigint,integer) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payment_provider_invoice(bigint,text,boolean) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payout_order(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payout_order_exists(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payout_referral(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_payout_review(integer) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_referral_payout_review(integer) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b2_payment_latest(bigint),public.bot_b2_payment_recent(bigint,integer),public.bot_b2_payment_provider_invoice(bigint,text,boolean),public.bot_b2_payout_order(bigint),public.bot_b2_payout_order_exists(bigint),public.bot_b2_payout_referral(bigint),public.bot_b2_payout_review(integer),public.bot_b2_referral_payout_review(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b2_payment_latest(bigint),public.bot_b2_payment_recent(bigint,integer),public.bot_b2_payment_provider_invoice(bigint,text,boolean),public.bot_b2_payout_order(bigint),public.bot_b2_payout_order_exists(bigint),public.bot_b2_payout_referral(bigint),public.bot_b2_payout_review(integer),public.bot_b2_referral_payout_review(integer) TO obsidian_exchange_bot;
