-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after 035-039.
GRANT SELECT(id,code,discount_percent,uses_count,max_uses,valid_until,is_active) ON public.promo_codes TO obsidian_exchange_bot_owner;
GRANT SELECT(provider,avg_response_time,failed_count,last_checked,is_healthy,status,blocker) ON public.provider_health TO obsidian_exchange_bot_owner;
GRANT SELECT(provider,ts,success) ON public.provider_attempts TO obsidian_exchange_bot_owner;
GRANT SELECT(id,user_id,currency,crypto_amount,rub_amount,sbp_phone,receive_address,tx_hash,status,payout_method,payout_bank,payout_details,payout_name,payout_provider,payout_ref,payout_status,created_at,updated_at) ON public.sell_orders TO obsidian_exchange_bot_owner;
GRANT SELECT(id,user_id,username,subject,status,updated_at) ON public.support_tickets TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b2_active_promos(a_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_limit<1 OR a_limit>100 THEN RAISE EXCEPTION 'invalid_limit'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.id DESC) FROM (SELECT p.id,p.code,p.discount_percent,p.uses_count,p.max_uses,p.valid_until FROM public.promo_codes p WHERE p.is_active=true ORDER BY p.id DESC LIMIT a_limit) q),'[]'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_provider_health_all() RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY q.provider),'[]'::jsonb) FROM (SELECT p.provider,p.avg_response_time,p.failed_count,p.last_checked,p.is_healthy,p.status,p.blocker FROM public.provider_health p) q $$;
CREATE OR REPLACE FUNCTION public.bot_b2_provider_attempt_stats(a_provider text,a_since timestamptz) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN a_provider=trim(a_provider); IF a_provider='' OR length(a_provider)>64 OR a_since IS NULL OR a_since>statement_timestamp() OR a_since<statement_timestamp()-interval '31 days' THEN RAISE EXCEPTION 'invalid_attempt_window'; END IF; RETURN (SELECT jsonb_build_object('count',count(*),'success',count(*) FILTER(WHERE p.success)) FROM public.provider_attempts p WHERE p.provider=a_provider AND p.ts>=a_since); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_sell_order(a_sell_id bigint) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_sell_id<=0 THEN RAISE EXCEPTION 'invalid_sell'; END IF; RETURN (SELECT to_jsonb(s) FROM public.sell_orders s WHERE s.id=a_sell_id); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_support_open_count() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT count(*) FROM public.support_tickets t WHERE t.status IN('open','answered') $$;
CREATE OR REPLACE FUNCTION public.bot_b2_support_staff_new(a_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_limit<1 OR a_limit>100 THEN RAISE EXCEPTION 'invalid_limit'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at,q.id) FROM (SELECT t.id,t.username,t.user_id,t.subject,t.updated_at FROM public.support_tickets t WHERE t.status='open' ORDER BY t.updated_at,t.id LIMIT a_limit) q),'[]'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_support_staff_open(a_limit integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_limit<1 OR a_limit>100 THEN RAISE EXCEPTION 'invalid_limit'; END IF; RETURN COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at DESC,q.id DESC) FROM (SELECT t.id,t.user_id,t.username,t.subject,t.status,t.updated_at FROM public.support_tickets t WHERE t.status IN('open','answered') ORDER BY t.updated_at DESC,t.id DESC LIMIT a_limit) q),'[]'::jsonb); END $$;

ALTER FUNCTION public.bot_b2_active_promos(integer) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_provider_health_all() OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_provider_attempt_stats(text,timestamptz) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_sell_order(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_support_open_count() OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_support_staff_new(integer) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_support_staff_open(integer) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b2_active_promos(integer),public.bot_b2_provider_health_all(),public.bot_b2_provider_attempt_stats(text,timestamptz),public.bot_b2_sell_order(bigint),public.bot_b2_support_open_count(),public.bot_b2_support_staff_new(integer),public.bot_b2_support_staff_open(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b2_active_promos(integer),public.bot_b2_provider_health_all(),public.bot_b2_provider_attempt_stats(text,timestamptz),public.bot_b2_sell_order(bigint),public.bot_b2_support_open_count(),public.bot_b2_support_staff_new(integer),public.bot_b2_support_staff_open(integer) TO obsidian_exchange_bot;
