-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after 035.
GRANT SELECT(order_id,user_id,currency,rub_amount,status,created_at) ON public.orders TO obsidian_exchange_bot_owner;
GRANT SELECT(currency,amount,updated_at) ON public.reserves TO obsidian_exchange_bot_owner;
GRANT SELECT(status) ON public.limit_orders,public.dca_schedules TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b2_reserves_detailed() RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY q.currency),'[]'::jsonb) FROM (SELECT r.currency,r.amount,r.updated_at FROM public.reserves r ORDER BY r.currency LIMIT 100) q $$;
CREATE OR REPLACE FUNCTION public.bot_b2_today_summary() RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT jsonb_build_object('today_count',count(*) FILTER(WHERE o.created_at>=CURRENT_DATE AND o.created_at<CURRENT_DATE+1),'today_volume',COALESCE(sum(o.rub_amount) FILTER(WHERE o.created_at>=CURRENT_DATE AND o.created_at<CURRENT_DATE+1),0),'today_sent',count(*) FILTER(WHERE o.created_at>=CURRENT_DATE AND o.created_at<CURRENT_DATE+1 AND o.status='sent'),'today_sent_volume',COALESCE(sum(o.rub_amount) FILTER(WHERE o.created_at>=CURRENT_DATE AND o.created_at<CURRENT_DATE+1 AND o.status='sent'),0),'pending',count(*) FILTER(WHERE o.status='pending'),'paid',count(*) FILTER(WHERE o.status='paid'),'new_users',(SELECT count(DISTINCT n.user_id) FROM public.orders n WHERE n.created_at>=CURRENT_DATE AND NOT EXISTS(SELECT 1 FROM public.orders old WHERE old.user_id=n.user_id AND old.created_at<CURRENT_DATE)),'active_limits',(SELECT count(*) FROM public.limit_orders l WHERE l.status='active'),'active_dca',(SELECT count(*) FROM public.dca_schedules d WHERE d.status='active')) FROM public.orders o
$$;
CREATE OR REPLACE FUNCTION public.bot_b2_period_order_report(a_from date,a_to date) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r jsonb; BEGIN
 IF a_from IS NULL OR a_to IS NULL OR a_from>a_to OR a_to-a_from>366 THEN RAISE EXCEPTION 'invalid_report_period'; END IF;
 SELECT jsonb_build_object('sent_count',count(*) FILTER(WHERE o.status='sent'),'sent_volume',COALESCE(sum(o.rub_amount) FILTER(WHERE o.status='sent'),0),'total_count',count(*),'currencies',COALESCE((SELECT jsonb_agg(jsonb_build_array(c.currency,c.n,c.volume) ORDER BY c.volume DESC,c.currency) FROM (SELECT x.currency,count(*) n,COALESCE(sum(x.rub_amount),0) volume FROM public.orders x WHERE x.created_at::date BETWEEN a_from AND a_to AND x.status='sent' GROUP BY x.currency ORDER BY volume DESC,x.currency LIMIT 100) c),'[]'::jsonb),'new_users',(SELECT count(DISTINCT n.user_id) FROM public.orders n WHERE n.created_at::date BETWEEN a_from AND a_to AND n.user_id>0 AND NOT EXISTS(SELECT 1 FROM public.orders old WHERE old.user_id=n.user_id AND old.created_at::date<a_from))) INTO r FROM public.orders o WHERE o.created_at::date BETWEEN a_from AND a_to;
 RETURN r;
END $$;
CREATE OR REPLACE FUNCTION public.bot_b2_cumulative_stats(a_starts jsonb,a_month_start date,a_currencies jsonb,a_statuses jsonb) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r jsonb; BEGIN
 IF a_month_start IS NULL OR jsonb_typeof(a_starts)<>'object' OR jsonb_typeof(a_currencies)<>'array' OR jsonb_typeof(a_statuses)<>'array' OR (SELECT count(*) FROM jsonb_object_keys(a_starts))>32 OR jsonb_array_length(a_currencies)>32 OR jsonb_array_length(a_statuses)>32 THEN RAISE EXCEPTION 'invalid_cumulative_inputs'; END IF;
 IF EXISTS(SELECT 1 FROM jsonb_each_text(a_starts) e WHERE length(e.key)>64 OR length(e.value)>10) OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(a_currencies) x WHERE x='' OR length(x)>32) OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(a_statuses) x WHERE x='' OR length(x)>32) THEN RAISE EXCEPTION 'invalid_cumulative_member'; END IF;
 PERFORM e.value::date FROM jsonb_each_text(a_starts) e;
 SELECT jsonb_build_object('periods',COALESCE((SELECT jsonb_object_agg(e.key,jsonb_build_array((SELECT count(*) FROM public.orders o WHERE o.created_at::date>=e.value::date AND o.status='sent'),(SELECT COALESCE(sum(o.rub_amount),0) FROM public.orders o WHERE o.created_at::date>=e.value::date AND o.status='sent'))) FROM jsonb_each_text(a_starts) e),'{}'::jsonb),'currencies',COALESCE((SELECT jsonb_object_agg(x.value,jsonb_build_array((SELECT count(*) FROM public.orders o WHERE o.created_at::date>=a_month_start AND o.currency=x.value AND o.status='sent'),(SELECT COALESCE(sum(o.rub_amount),0) FROM public.orders o WHERE o.created_at::date>=a_month_start AND o.currency=x.value AND o.status='sent'))) FROM jsonb_array_elements_text(a_currencies) x),'{}'::jsonb),'statuses',COALESCE((SELECT jsonb_object_agg(x.value,(SELECT count(*) FROM public.orders o WHERE o.created_at::date>=a_month_start AND o.status=x.value)) FROM jsonb_array_elements_text(a_statuses) x),'{}'::jsonb)) INTO r;
 RETURN r;
END $$;

ALTER FUNCTION public.bot_b2_reserves_detailed() OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_today_summary() OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_period_order_report(date,date) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b2_cumulative_stats(jsonb,date,jsonb,jsonb) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b2_reserves_detailed(),public.bot_b2_today_summary(),public.bot_b2_period_order_report(date,date),public.bot_b2_cumulative_stats(jsonb,date,jsonb,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b2_reserves_detailed(),public.bot_b2_today_summary(),public.bot_b2_period_order_report(date,date),public.bot_b2_cumulative_stats(jsonb,date,jsonb,jsonb) TO obsidian_exchange_bot;
