-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after role envelope.
GRANT SELECT(id),INSERT(admin_id,action,target_id,details) ON public.admin_log TO obsidian_exchange_bot_owner;
GRANT USAGE,SELECT ON SEQUENCE public.admin_log_id_seq TO obsidian_exchange_bot_owner;
GRANT SELECT(user_id,broadcast_enabled),UPDATE(broadcast_enabled) ON public.bot_users TO obsidian_exchange_bot_owner;
GRANT SELECT(user_id,enabled,last_notified,last_btc,last_ltc,last_usdt),INSERT(user_id),UPDATE(enabled,last_notified,last_btc,last_ltc,last_usdt) ON public.rate_subscriptions TO obsidian_exchange_bot_owner;
GRANT SELECT(order_id,user_id) ON public.orders TO obsidian_exchange_bot_owner;
GRANT SELECT(id,order_id,user_id,rating,comment,status),UPDATE(rating,comment,status) ON public.reviews TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b3_log_action(a_actor bigint,a_action text,a_target bigint,a_details text) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE ident bigint; BEGIN a_action=trim(a_action); IF a_actor<=0 OR a_action='' OR length(a_action)>80 OR (a_details IS NOT NULL AND length(a_details)>500) THEN RAISE EXCEPTION 'invalid_audit'; END IF; INSERT INTO public.admin_log(admin_id,action,target_id,details) VALUES(a_actor,a_action,a_target,a_details) RETURNING id INTO ident; RETURN ident; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_disable_broadcast(a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_user_id<=0 THEN RAISE EXCEPTION 'invalid_owner'; END IF; UPDATE public.bot_users SET broadcast_enabled=false WHERE user_id=a_user_id AND broadcast_enabled=true; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_disable_rates(a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_user_id<=0 THEN RAISE EXCEPTION 'invalid_owner'; END IF; UPDATE public.rate_subscriptions SET enabled=false WHERE user_id=a_user_id; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_toggle_rate(a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE state boolean; BEGIN IF a_user_id<=0 THEN RAISE EXCEPTION 'invalid_owner'; END IF; INSERT INTO public.rate_subscriptions(user_id) VALUES(a_user_id) ON CONFLICT(user_id) DO NOTHING; UPDATE public.rate_subscriptions SET enabled=NOT enabled WHERE user_id=a_user_id RETURNING enabled INTO state; IF state IS NULL THEN RAISE EXCEPTION 'toggle_lost'; END IF; RETURN state; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_update_rates(a_user_id bigint,a_notified double precision,a_btc numeric,a_ltc numeric,a_usdt numeric) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_user_id<=0 OR a_notified IS NULL OR a_btc IS NULL OR a_ltc IS NULL OR a_usdt IS NULL OR a_notified<0 OR a_btc<0 OR a_ltc<0 OR a_usdt<0 THEN RAISE EXCEPTION 'invalid_rates'; END IF; UPDATE public.rate_subscriptions SET last_notified=a_notified,last_btc=a_btc,last_ltc=a_ltc,last_usdt=a_usdt WHERE user_id=a_user_id; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_rate_review(a_order_id bigint,a_user_id bigint,a_rating integer) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 OR a_user_id<=0 OR a_rating<1 OR a_rating>5 THEN RAISE EXCEPTION 'invalid_review'; END IF; UPDATE public.reviews r SET rating=a_rating,status='pending_comment' WHERE r.order_id=a_order_id AND r.user_id=a_user_id AND r.status='pending_rating' AND EXISTS(SELECT 1 FROM public.orders o WHERE o.order_id=r.order_id AND o.user_id=a_user_id); RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_comment_review(a_order_id bigint,a_user_id bigint,a_comment text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_order_id<=0 OR a_user_id<=0 OR a_comment IS NULL OR length(a_comment)>2000 THEN RAISE EXCEPTION 'invalid_review_comment'; END IF; UPDATE public.reviews r SET comment=a_comment WHERE r.order_id=a_order_id AND r.user_id=a_user_id AND r.status='pending_comment' AND EXISTS(SELECT 1 FROM public.orders o WHERE o.order_id=r.order_id AND o.user_id=a_user_id); RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_finalize_review(a_order_id bigint,a_user_id bigint) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE rr_id bigint; rr_user bigint; rr_rating integer; rr_comment text; target text; BEGIN IF a_order_id<=0 OR a_user_id<=0 THEN RAISE EXCEPTION 'invalid_review'; END IF; SELECT r.id,r.user_id,r.rating,r.comment INTO rr_id,rr_user,rr_rating,rr_comment FROM public.reviews r WHERE r.order_id=a_order_id AND r.user_id=a_user_id AND r.status='pending_comment' AND EXISTS(SELECT 1 FROM public.orders o WHERE o.order_id=r.order_id AND o.user_id=a_user_id) FOR UPDATE; IF NOT FOUND THEN RETURN NULL; END IF; target=CASE WHEN rr_rating>=4 THEN 'published' ELSE 'admin_review' END; UPDATE public.reviews r SET status=target WHERE r.id=rr_id AND r.status='pending_comment' AND EXISTS(SELECT 1 FROM public.orders o WHERE o.order_id=r.order_id AND o.user_id=a_user_id); IF NOT FOUND THEN RAISE EXCEPTION 'review_finalize_lost'; END IF; RETURN jsonb_build_object('user_id',rr_user,'rating',rr_rating,'comment',rr_comment,'status',target); END $$;

ALTER FUNCTION public.bot_b3_log_action(bigint,text,bigint,text) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_disable_broadcast(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_disable_rates(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_toggle_rate(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_update_rates(bigint,double precision,numeric,numeric,numeric) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_rate_review(bigint,bigint,integer) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_comment_review(bigint,bigint,text) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_finalize_review(bigint,bigint) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b3_log_action(bigint,text,bigint,text),public.bot_b3_disable_broadcast(bigint),public.bot_b3_disable_rates(bigint),public.bot_b3_toggle_rate(bigint),public.bot_b3_update_rates(bigint,double precision,numeric,numeric,numeric),public.bot_b3_rate_review(bigint,bigint,integer),public.bot_b3_comment_review(bigint,bigint,text),public.bot_b3_finalize_review(bigint,bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b3_log_action(bigint,text,bigint,text),public.bot_b3_disable_broadcast(bigint),public.bot_b3_disable_rates(bigint),public.bot_b3_toggle_rate(bigint),public.bot_b3_update_rates(bigint,double precision,numeric,numeric,numeric),public.bot_b3_rate_review(bigint,bigint,integer),public.bot_b3_comment_review(bigint,bigint,text),public.bot_b3_finalize_review(bigint,bigint) TO obsidian_exchange_bot;
