-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after role envelope.
GRANT SELECT(user_id),INSERT(user_id,reason),DELETE ON public.blocked_users TO obsidian_exchange_bot_owner;
GRANT SELECT(address,reason,blocked_by),INSERT(address,reason,blocked_by),UPDATE(reason,blocked_by),DELETE ON public.blocked_addresses TO obsidian_exchange_bot_owner;
GRANT SELECT(user_id,username,is_active),INSERT(user_id,username,added_by),UPDATE(username,is_active) ON public.operators TO obsidian_exchange_bot_owner;
GRANT SELECT(user_id,username,is_active),INSERT(user_id,username,added_by),UPDATE(username,is_active) ON public.workers TO obsidian_exchange_bot_owner;
GRANT SELECT(currency,amount,updated_at),INSERT(currency,amount,updated_at),UPDATE(amount,updated_at) ON public.reserves TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b3_admin_block_user(a_user_id bigint,a_reason text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_user_id<=0 OR a_reason IS NULL OR length(trim(a_reason))<1 OR length(a_reason)>500 THEN RAISE EXCEPTION 'invalid_block_user'; END IF; INSERT INTO public.blocked_users(user_id,reason) VALUES(a_user_id,a_reason) ON CONFLICT(user_id) DO NOTHING; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_unblock_user(a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_user_id<=0 THEN RAISE EXCEPTION 'invalid_unblock_user'; END IF; DELETE FROM public.blocked_users WHERE user_id=a_user_id; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_block_address(a_address text,a_reason text,a_actor bigint) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_address IS NULL OR length(trim(a_address))<1 OR length(a_address)>512 OR a_reason IS NULL OR length(trim(a_reason))<1 OR length(a_reason)>500 OR a_actor<=0 THEN RAISE EXCEPTION 'invalid_block_address'; END IF; INSERT INTO public.blocked_addresses(address,reason,blocked_by) VALUES(a_address,a_reason,a_actor) ON CONFLICT(address) DO UPDATE SET reason=excluded.reason,blocked_by=excluded.blocked_by; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_unblock_addresses(a_addresses text[]) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE removed integer; BEGIN IF a_addresses IS NULL OR cardinality(a_addresses)>100 OR EXISTS(SELECT 1 FROM unnest(a_addresses) a WHERE a IS NULL OR length(trim(a))<1 OR length(a)>512) THEN RAISE EXCEPTION 'invalid_unblock_addresses'; END IF; IF cardinality(a_addresses)=0 THEN RETURN 0; END IF; DELETE FROM public.blocked_addresses b WHERE b.address=ANY(a_addresses); GET DIAGNOSTICS removed=ROW_COUNT; RETURN removed; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_set_staff(a_role text,a_user_id bigint,a_username text,a_actor bigint) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_role NOT IN('worker','operator') OR a_user_id<=0 OR a_actor<=0 OR (a_username IS NOT NULL AND length(a_username)>64) THEN RAISE EXCEPTION 'invalid_staff'; END IF; IF a_role='worker' THEN INSERT INTO public.workers(user_id,username,added_by) VALUES(a_user_id,a_username,a_actor) ON CONFLICT(user_id) DO UPDATE SET is_active=true,username=excluded.username; ELSE INSERT INTO public.operators(user_id,username,added_by) VALUES(a_user_id,a_username,a_actor) ON CONFLICT(user_id) DO UPDATE SET is_active=true,username=excluded.username; END IF; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_deactivate_staff(a_role text,a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_role NOT IN('worker','operator') OR a_user_id<=0 THEN RAISE EXCEPTION 'invalid_staff'; END IF; IF a_role='worker' THEN UPDATE public.workers SET is_active=false WHERE user_id=a_user_id AND is_active=true; ELSE UPDATE public.operators SET is_active=false WHERE user_id=a_user_id AND is_active=true; END IF; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b3_admin_set_reserve(a_currency text,a_amount numeric) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN a_currency=upper(trim(a_currency)); IF a_currency IS NULL OR length(a_currency)<2 OR length(a_currency)>16 OR a_currency !~ '^[A-Z0-9]+$' OR a_amount IS NULL OR a_amount<0 THEN RAISE EXCEPTION 'invalid_reserve'; END IF; INSERT INTO public.reserves(currency,amount,updated_at) VALUES(a_currency,a_amount,clock_timestamp()) ON CONFLICT(currency) DO UPDATE SET amount=excluded.amount,updated_at=excluded.updated_at; END $$;

ALTER FUNCTION public.bot_b3_admin_block_user(bigint,text) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_unblock_user(bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_block_address(text,text,bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_unblock_addresses(text[]) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_set_staff(text,bigint,text,bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_deactivate_staff(text,bigint) OWNER TO obsidian_exchange_bot_owner; ALTER FUNCTION public.bot_b3_admin_set_reserve(text,numeric) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b3_admin_block_user(bigint,text),public.bot_b3_admin_unblock_user(bigint),public.bot_b3_admin_block_address(text,text,bigint),public.bot_b3_admin_unblock_addresses(text[]),public.bot_b3_admin_set_staff(text,bigint,text,bigint),public.bot_b3_admin_deactivate_staff(text,bigint),public.bot_b3_admin_set_reserve(text,numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b3_admin_block_user(bigint,text),public.bot_b3_admin_unblock_user(bigint),public.bot_b3_admin_block_address(text,text,bigint),public.bot_b3_admin_unblock_addresses(text[]),public.bot_b3_admin_set_staff(text,bigint,text,bigint),public.bot_b3_admin_deactivate_staff(text,bigint),public.bot_b3_admin_set_reserve(text,numeric) TO obsidian_exchange_bot;
