-- E0.3 PROPOSAL ONLY. Disposable PostgreSQL 17 rehearsal after role envelope.
GRANT SELECT(order_id,user_id,rub_amount,currency,status,created_at,montera_invoice_id,receipt_sent_at,receipt_deadline,paid_btc_tx,updated_at) ON public.orders TO obsidian_exchange_bot_owner;
GRANT UPDATE(order_id) ON public.orders TO obsidian_exchange_bot_owner;
GRANT SELECT(id,order_id,status,session_token) ON public.payment_sessions TO obsidian_exchange_bot_owner;
GRANT SELECT(order_id) ON public.order_receipts TO obsidian_exchange_bot_owner;
GRANT SELECT(order_id,event),INSERT(order_id,event) ON public.sent_notifications TO obsidian_exchange_bot_owner;
GRANT SELECT(user_id) ON public.blocked_users TO obsidian_exchange_bot_owner;
GRANT SELECT(id),INSERT(code,discount_percent,max_uses,valid_until,is_active) ON public.promo_codes TO obsidian_exchange_bot_owner;
GRANT USAGE ON SEQUENCE public.promo_codes_id_seq TO obsidian_exchange_bot_owner;
GRANT SELECT(id,kind,dedupe_key,payload,state,attempts),INSERT(kind,dedupe_key,payload),UPDATE(state,attempts,claimed_at,sent_at,updated_at) ON public.bot_notification_jobs TO obsidian_exchange_bot_owner;
GRANT USAGE ON SEQUENCE public.bot_notification_jobs_id_seq TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b5_notification_claim(a_kind text) RETURNS TABLE(id bigint,kind text,dedupe_key text,payload jsonb,attempts integer) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN
 IF a_kind IS NOT NULL AND a_kind NOT IN('recall','montera_customer','montera_admin','pay_reminder','payout_delayed','winback_promo') THEN RAISE EXCEPTION 'invalid_notification_kind'; END IF;
 RETURN QUERY WITH candidate AS (SELECT j.id FROM public.bot_notification_jobs j WHERE j.state='pending' AND (a_kind IS NULL OR j.kind=a_kind) ORDER BY j.attempts,j.id FOR UPDATE SKIP LOCKED LIMIT 1)
 UPDATE public.bot_notification_jobs j SET state='sending',attempts=j.attempts+1,claimed_at=clock_timestamp(),updated_at=clock_timestamp() FROM candidate c WHERE j.id=c.id AND j.state='pending' RETURNING j.id,j.kind,j.dedupe_key,j.payload,j.attempts;
END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_notification_mark_sent(a_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 THEN RAISE EXCEPTION 'invalid_notification_id'; END IF; UPDATE public.bot_notification_jobs SET state='sent',sent_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=a_id AND state='sending'; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_notification_retry(a_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 THEN RAISE EXCEPTION 'invalid_notification_id'; END IF; UPDATE public.bot_notification_jobs SET state='pending',claimed_at=NULL,updated_at=clock_timestamp() WHERE id=a_id AND state='sending'; RETURN FOUND; END $$;

CREATE OR REPLACE FUNCTION public.bot_b5_queue_due_abandoned(a_now timestamptz,a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;n integer:=0;lim integer; BEGIN
 IF a_now IS NULL OR a_limit IS NULL THEN RAISE EXCEPTION 'invalid_queue_args'; END IF;lim=greatest(1,least(a_limit,1000));
 FOR r IN SELECT o.order_id,o.user_id,o.rub_amount,o.currency,(SELECT ps.session_token FROM public.payment_sessions ps WHERE ps.order_id=o.order_id AND ps.status NOT IN('failed','expired') ORDER BY ps.id DESC LIMIT 1) session_token FROM public.orders o WHERE o.user_id>0 AND o.status='pending' AND o.created_at BETWEEN a_now-interval '13 minutes' AND a_now-interval '8 minutes' AND NOT EXISTS(SELECT 1 FROM public.order_receipts x WHERE x.order_id=o.order_id) AND NOT EXISTS(SELECT 1 FROM public.sent_notifications s WHERE s.order_id=o.order_id AND s.event='pay_reminder') ORDER BY o.order_id FOR UPDATE OF o SKIP LOCKED LIMIT lim LOOP
  INSERT INTO public.sent_notifications(order_id,event) VALUES(r.order_id,'pay_reminder') ON CONFLICT DO NOTHING;IF NOT FOUND THEN CONTINUE;END IF;
  INSERT INTO public.bot_notification_jobs(kind,dedupe_key,payload) VALUES('pay_reminder',r.order_id::text,jsonb_build_object('order_id',r.order_id,'user_id',r.user_id,'rub_amount',r.rub_amount,'currency',r.currency,'session_token',r.session_token));n=n+1;
 END LOOP;RETURN n;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_queue_due_montera(a_now timestamptz,a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;n integer:=0;lim integer; BEGIN
 IF a_now IS NULL OR a_limit IS NULL THEN RAISE EXCEPTION 'invalid_queue_args'; END IF;lim=greatest(1,least(a_limit,1000));
 FOR r IN SELECT o.order_id,o.user_id,o.montera_invoice_id,EXISTS(SELECT 1 FROM public.order_receipts x WHERE x.order_id=o.order_id) has_file FROM public.orders o WHERE o.user_id>0 AND o.status='pending' AND o.receipt_sent_at IS NULL AND o.receipt_deadline BETWEEN a_now+interval '8 minutes' AND a_now+interval '12 minutes' AND NOT EXISTS(SELECT 1 FROM public.sent_notifications s WHERE s.order_id=o.order_id AND s.event='receipt_reminder') ORDER BY o.order_id FOR UPDATE OF o SKIP LOCKED LIMIT lim LOOP
  INSERT INTO public.sent_notifications(order_id,event) VALUES(r.order_id,'receipt_reminder') ON CONFLICT DO NOTHING;IF NOT FOUND THEN CONTINUE;END IF;
  INSERT INTO public.bot_notification_jobs(kind,dedupe_key,payload) SELECT k,r.order_id::text,jsonb_build_object('order_id',r.order_id,'user_id',r.user_id,'invoice_id',r.montera_invoice_id,'has_file',r.has_file) FROM unnest(ARRAY['montera_customer','montera_admin']) k;n=n+1;
 END LOOP;RETURN n;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_queue_due_payout_delays(a_warn_minutes integer,a_now timestamptz,a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;n integer:=0;lim integer; BEGIN
 IF a_now IS NULL OR a_limit IS NULL OR a_warn_minutes IS NULL OR a_warn_minutes<0 OR a_warn_minutes>10080 THEN RAISE EXCEPTION 'invalid_queue_args'; END IF;lim=greatest(1,least(a_limit,1000));
 FOR r IN SELECT o.order_id,o.user_id,o.currency FROM public.orders o WHERE o.user_id>0 AND o.status='paid' AND coalesce(o.paid_btc_tx,'')='' AND coalesce(o.updated_at,o.created_at)<=a_now-(a_warn_minutes*interval '1 minute') AND NOT EXISTS(SELECT 1 FROM public.sent_notifications s WHERE s.order_id=o.order_id AND s.event='payout_delayed') ORDER BY coalesce(o.updated_at,o.created_at),o.order_id FOR UPDATE OF o SKIP LOCKED LIMIT lim LOOP
  INSERT INTO public.sent_notifications(order_id,event) VALUES(r.order_id,'payout_delayed') ON CONFLICT DO NOTHING;IF NOT FOUND THEN CONTINUE;END IF;INSERT INTO public.bot_notification_jobs(kind,dedupe_key,payload) VALUES('payout_delayed',r.order_id::text,jsonb_build_object('order_id',r.order_id,'user_id',r.user_id,'currency',r.currency));n=n+1;
 END LOOP;RETURN n;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_queue_due_recalls(a_now timestamptz,a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;n integer:=0;lim integer; BEGIN
 IF a_now IS NULL OR a_limit IS NULL THEN RAISE EXCEPTION 'invalid_queue_args'; END IF;lim=greatest(1,least(a_limit,1000));
 FOR r IN SELECT DISTINCT o.user_id FROM public.orders o WHERE o.user_id>0 AND o.status='sent' AND NOT EXISTS(SELECT 1 FROM public.orders recent WHERE recent.user_id=o.user_id AND recent.created_at>a_now-interval '14 days') AND NOT EXISTS(SELECT 1 FROM public.sent_notifications s WHERE s.order_id=o.user_id AND s.event='recall') ORDER BY o.user_id LIMIT lim LOOP
  INSERT INTO public.sent_notifications(order_id,event) VALUES(r.user_id,'recall') ON CONFLICT DO NOTHING;IF NOT FOUND THEN CONTINUE;END IF;INSERT INTO public.bot_notification_jobs(kind,dedupe_key,payload) VALUES('recall',r.user_id::text,jsonb_build_object('user_id',r.user_id));n=n+1;
 END LOOP;RETURN n;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_queue_due_winbacks(a_discount numeric,a_valid_hours integer,a_now timestamptz,a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;n integer:=0;lim integer;code text;promo_id bigint; BEGIN
 IF a_now IS NULL OR a_limit IS NULL OR a_discount IS NULL OR a_discount::text IN('NaN','Infinity','-Infinity') OR a_discount<=0 OR a_discount>100 OR a_valid_hours IS NULL OR a_valid_hours<1 OR a_valid_hours>8760 THEN RAISE EXCEPTION 'invalid_winback_args'; END IF;lim=greatest(1,least(a_limit,1000));
 FOR r IN SELECT max(o.order_id) order_id,o.user_id FROM public.orders o WHERE o.user_id>0 AND o.status='expired' AND o.updated_at BETWEEN a_now-interval '48 hours' AND a_now-interval '1 hour' AND NOT EXISTS(SELECT 1 FROM public.orders paid WHERE paid.user_id=o.user_id AND paid.status IN('paid','sent')) AND NOT EXISTS(SELECT 1 FROM public.order_receipts x JOIN public.orders ro ON ro.order_id=x.order_id WHERE ro.user_id=o.user_id) AND NOT EXISTS(SELECT 1 FROM public.sent_notifications s JOIN public.orders mo ON mo.order_id=s.order_id WHERE mo.user_id=o.user_id AND s.event='winback_promo') AND NOT EXISTS(SELECT 1 FROM public.blocked_users b WHERE b.user_id=o.user_id) GROUP BY o.user_id ORDER BY o.user_id LIMIT lim LOOP
  INSERT INTO public.sent_notifications(order_id,event) VALUES(r.order_id,'winback_promo') ON CONFLICT DO NOTHING;IF NOT FOUND THEN CONTINUE;END IF;code='BACK'||trunc(a_discount)::text||'-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,6));
  INSERT INTO public.promo_codes(code,discount_percent,max_uses,valid_until,is_active) VALUES(code,a_discount,1,a_now+(a_valid_hours*interval '1 hour'),true) RETURNING id INTO promo_id;
  INSERT INTO public.bot_notification_jobs(kind,dedupe_key,payload) VALUES('winback_promo',r.order_id::text,jsonb_build_object('order_id',r.order_id,'user_id',r.user_id,'code',code,'code_id',promo_id,'discount',a_discount,'valid_hours',a_valid_hours,'valid_until',a_now+(a_valid_hours*interval '1 hour')));n=n+1;
 END LOOP;RETURN n;END $$;

ALTER FUNCTION public.bot_b5_notification_claim(text) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_notification_mark_sent(bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_notification_retry(bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_queue_due_abandoned(timestamptz,integer) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_queue_due_montera(timestamptz,integer) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_queue_due_payout_delays(integer,timestamptz,integer) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_queue_due_recalls(timestamptz,integer) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_queue_due_winbacks(numeric,integer,timestamptz,integer) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b5_notification_claim(text),public.bot_b5_notification_mark_sent(bigint),public.bot_b5_notification_retry(bigint),public.bot_b5_queue_due_abandoned(timestamptz,integer),public.bot_b5_queue_due_montera(timestamptz,integer),public.bot_b5_queue_due_payout_delays(integer,timestamptz,integer),public.bot_b5_queue_due_recalls(timestamptz,integer),public.bot_b5_queue_due_winbacks(numeric,integer,timestamptz,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b5_notification_claim(text),public.bot_b5_notification_mark_sent(bigint),public.bot_b5_notification_retry(bigint),public.bot_b5_queue_due_abandoned(timestamptz,integer),public.bot_b5_queue_due_montera(timestamptz,integer),public.bot_b5_queue_due_payout_delays(integer,timestamptz,integer),public.bot_b5_queue_due_recalls(timestamptz,integer),public.bot_b5_queue_due_winbacks(numeric,integer,timestamptz,integer) TO obsidian_exchange_bot;
