-- E0.3 PROPOSAL ONLY. Automation/value writers; gift redemption remains NO_ROLLOUT until immutable redemption ledger.
GRANT SELECT(id,user_id,currency,rub_amount,interval_days,status,next_run,runs_total),UPDATE(status,next_run,runs_total) ON public.dca_schedules TO obsidian_exchange_bot_owner;
GRANT SELECT(id,user_id,currency,rub_amount,status,expires_at),UPDATE(status,triggered_at,order_id) ON public.limit_orders TO obsidian_exchange_bot_owner;
GRANT SELECT(order_id),INSERT(user_id,username,currency,rub_amount,crypto_address,status,agreed_rate,agreed_crypto_amount,agreed_at) ON public.orders TO obsidian_exchange_bot_owner;
GRANT USAGE ON SEQUENCE public.orders_order_id_seq TO obsidian_exchange_bot_owner;
GRANT SELECT(id,code,currency,rub_amount,sender_id,status),INSERT(sender_id,currency,rub_amount,code,order_id),UPDATE(status,recipient_id,recipient_address,claimed_at) ON public.gift_vouchers TO obsidian_exchange_bot_owner;
GRANT USAGE ON SEQUENCE public.gift_vouchers_id_seq TO obsidian_exchange_bot_owner;

CREATE OR REPLACE FUNCTION public.bot_b5_dca_cancel(a_id bigint,a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 OR a_user_id IS NULL OR a_user_id<=0 THEN RAISE EXCEPTION 'invalid_dca_cancel';END IF;UPDATE public.dca_schedules SET status='cancelled' WHERE id=a_id AND user_id=a_user_id AND status='active';RETURN FOUND;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_limit_cancel(a_id bigint,a_user_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 OR a_user_id IS NULL OR a_user_id<=0 THEN RAISE EXCEPTION 'invalid_limit_cancel';END IF;UPDATE public.limit_orders SET status='cancelled' WHERE id=a_id AND user_id=a_user_id AND status='active';RETURN FOUND;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_limit_expire(a_limit integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE n integer;BEGIN IF a_limit IS NULL OR a_limit<1 OR a_limit>100 THEN RAISE EXCEPTION 'invalid_expire_limit';END IF;WITH due AS(SELECT id FROM public.limit_orders WHERE status='active' AND expires_at<=clock_timestamp() ORDER BY expires_at,id FOR UPDATE SKIP LOCKED LIMIT a_limit),changed AS(UPDATE public.limit_orders l SET status='expired' FROM due d WHERE l.id=d.id AND l.status='active' RETURNING l.id) SELECT count(*) INTO n FROM changed;RETURN n;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_dca_run(a_id bigint,a_expected timestamptz,a_destination text,a_rate numeric,a_crypto numeric) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;oid bigint;BEGIN a_destination=trim(a_destination);IF a_id IS NULL OR a_id<=0 OR a_expected IS NULL OR a_destination IS NULL OR length(a_destination)<1 OR length(a_destination)>512 OR a_rate IS NULL OR a_crypto IS NULL OR a_rate::text IN('NaN','Infinity','-Infinity') OR a_crypto::text IN('NaN','Infinity','-Infinity') OR least(a_rate,a_crypto)<=0 THEN RAISE EXCEPTION 'invalid_dca_run';END IF;SELECT user_id,currency,rub_amount,interval_days INTO r FROM public.dca_schedules WHERE id=a_id AND status='active' AND next_run=a_expected AND next_run<=clock_timestamp() FOR UPDATE;IF NOT FOUND THEN RETURN NULL;END IF;INSERT INTO public.orders(user_id,username,currency,rub_amount,crypto_address,status,agreed_rate,agreed_crypto_amount,agreed_at) VALUES(r.user_id,'dca_'||a_id,r.currency,r.rub_amount,a_destination,'pending',a_rate,a_crypto,clock_timestamp()) RETURNING order_id INTO oid;UPDATE public.dca_schedules SET next_run=a_expected+(r.interval_days*interval '1 day'),runs_total=runs_total+1 WHERE id=a_id AND status='active' AND next_run=a_expected;IF NOT FOUND THEN RAISE EXCEPTION 'dca_advance_lost';END IF;RETURN oid;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_limit_trigger(a_id bigint,a_expected timestamptz,a_destination text,a_rate numeric,a_crypto numeric) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;oid bigint;BEGIN a_destination=trim(a_destination);IF a_id IS NULL OR a_id<=0 OR a_expected IS NULL OR a_destination IS NULL OR length(a_destination)<1 OR length(a_destination)>512 OR a_rate IS NULL OR a_crypto IS NULL OR a_rate::text IN('NaN','Infinity','-Infinity') OR a_crypto::text IN('NaN','Infinity','-Infinity') OR least(a_rate,a_crypto)<=0 THEN RAISE EXCEPTION 'invalid_limit_trigger';END IF;SELECT user_id,currency,rub_amount INTO r FROM public.limit_orders WHERE id=a_id AND status='active' AND expires_at=a_expected AND expires_at>clock_timestamp() FOR UPDATE;IF NOT FOUND THEN RETURN NULL;END IF;INSERT INTO public.orders(user_id,username,currency,rub_amount,crypto_address,status,agreed_rate,agreed_crypto_amount,agreed_at) VALUES(r.user_id,'limit_order',r.currency,r.rub_amount,a_destination,'pending',a_rate,a_crypto,clock_timestamp()) RETURNING order_id INTO oid;UPDATE public.limit_orders SET status='triggered',triggered_at=clock_timestamp(),order_id=oid WHERE id=a_id AND status='active' AND expires_at=a_expected;IF NOT FOUND THEN RAISE EXCEPTION 'limit_trigger_lost';END IF;RETURN oid;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_gift_issue(a_sender bigint,a_currency text,a_rub numeric,a_code text,a_destination text,a_rate numeric,a_crypto numeric) RETURNS TABLE(order_id bigint,gift_id bigint) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE oid bigint;gid bigint;BEGIN a_currency=upper(trim(a_currency));a_code=upper(trim(a_code));a_destination=trim(a_destination);IF a_sender IS NULL OR a_sender<=0 OR a_currency NOT IN('BTC','LTC','USDT') OR a_rub IS NULL OR a_rub::text IN('NaN','Infinity','-Infinity') OR a_rub<=0 OR a_code IS NULL OR length(a_code)<6 OR length(a_code)>64 OR a_code !~ '^[A-Z0-9_-]+$' OR a_destination IS NULL OR length(a_destination)<1 OR length(a_destination)>512 OR a_rate IS NULL OR a_crypto IS NULL OR least(a_rate,a_crypto)<=0 THEN RAISE EXCEPTION 'invalid_gift_issue';END IF;INSERT INTO public.orders(user_id,username,currency,rub_amount,crypto_address,status,agreed_rate,agreed_crypto_amount,agreed_at) VALUES(a_sender,'gift_'||a_code,a_currency,a_rub,a_destination,'pending',a_rate,a_crypto,clock_timestamp()) RETURNING public.orders.order_id INTO oid;INSERT INTO public.gift_vouchers(sender_id,currency,rub_amount,code,order_id) VALUES(a_sender,a_currency,a_rub,a_code,oid) RETURNING id INTO gid;RETURN QUERY SELECT oid,gid;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_gift_redeem(a_gift_id bigint,a_recipient bigint,a_destination text,a_rate numeric,a_crypto numeric) RETURNS bigint LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE r record;oid bigint;BEGIN a_destination=trim(a_destination);IF a_gift_id IS NULL OR a_gift_id<=0 OR a_recipient IS NULL OR a_recipient<=0 OR a_destination IS NULL OR length(a_destination)<1 OR length(a_destination)>512 OR a_rate IS NULL OR a_crypto IS NULL OR least(a_rate,a_crypto)<=0 THEN RAISE EXCEPTION 'invalid_gift_redeem';END IF;SELECT currency,rub_amount,sender_id,status INTO r FROM public.gift_vouchers WHERE id=a_gift_id FOR UPDATE;IF NOT FOUND OR r.status<>'paid' OR r.sender_id=a_recipient THEN RETURN NULL;END IF;UPDATE public.gift_vouchers SET status='redeemed',recipient_id=a_recipient,recipient_address=a_destination,claimed_at=clock_timestamp() WHERE id=a_gift_id AND status='paid';IF NOT FOUND THEN RETURN NULL;END IF;INSERT INTO public.orders(user_id,username,currency,rub_amount,crypto_address,status,agreed_rate,agreed_crypto_amount,agreed_at) VALUES(a_recipient,'gift_redeem_'||a_gift_id,r.currency,r.rub_amount,a_destination,'paid',a_rate,a_crypto,clock_timestamp()) RETURNING order_id INTO oid;RETURN oid;END $$;
ALTER FUNCTION public.bot_b5_dca_cancel(bigint,bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_limit_cancel(bigint,bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_limit_expire(integer) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_dca_run(bigint,timestamptz,text,numeric,numeric) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_limit_trigger(bigint,timestamptz,text,numeric,numeric) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_gift_issue(bigint,text,numeric,text,text,numeric,numeric) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_gift_redeem(bigint,bigint,text,numeric,numeric) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b5_dca_cancel(bigint,bigint),public.bot_b5_limit_cancel(bigint,bigint),public.bot_b5_limit_expire(integer),public.bot_b5_dca_run(bigint,timestamptz,text,numeric,numeric),public.bot_b5_limit_trigger(bigint,timestamptz,text,numeric,numeric),public.bot_b5_gift_issue(bigint,text,numeric,text,text,numeric,numeric),public.bot_b5_gift_redeem(bigint,bigint,text,numeric,numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b5_dca_cancel(bigint,bigint),public.bot_b5_limit_cancel(bigint,bigint),public.bot_b5_limit_expire(integer),public.bot_b5_dca_run(bigint,timestamptz,text,numeric,numeric),public.bot_b5_limit_trigger(bigint,timestamptz,text,numeric,numeric),public.bot_b5_gift_issue(bigint,text,numeric,text,text,numeric,numeric),public.bot_b5_gift_redeem(bigint,bigint,text,numeric,numeric) TO obsidian_exchange_bot;
