-- E0.3 PROPOSAL ONLY. Redesigns notification delivery so ambiguous outcomes cannot be blindly retried.
ALTER TABLE public.notification_outbox DROP CONSTRAINT notification_outbox_state_check;
ALTER TABLE public.notification_outbox ADD CONSTRAINT notification_outbox_state_check CHECK(state IN('pending','sending','sent','review'));
ALTER TABLE public.notification_outbox ADD COLUMN attempt_token text;
ALTER TABLE public.notification_outbox ADD COLUMN review_reason text;
GRANT SELECT(id,topic,aggregate_id,recipient_id,payload,state,attempts,attempt_token),UPDATE(state,attempts,claimed_at,sent_at,updated_at,attempt_token,review_reason) ON public.notification_outbox TO obsidian_exchange_bot_owner;
CREATE OR REPLACE FUNCTION public.bot_b5_outbox_claim() RETURNS TABLE(id bigint,topic text,aggregate_id text,recipient_id bigint,payload jsonb,attempts integer,attempt_token text) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN RETURN QUERY WITH c AS(SELECT n.id FROM public.notification_outbox n WHERE n.state='pending' ORDER BY n.id FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE public.notification_outbox n SET state='sending',attempts=n.attempts+1,claimed_at=clock_timestamp(),updated_at=clock_timestamp(),attempt_token=md5(random()::text||clock_timestamp()::text||n.id::text),review_reason=NULL FROM c WHERE n.id=c.id AND n.state='pending' RETURNING n.id,n.topic,n.aggregate_id,n.recipient_id,n.payload,n.attempts,n.attempt_token;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_outbox_mark_sent(a_id bigint,a_token text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 OR a_token IS NULL OR length(a_token)<>32 THEN RAISE EXCEPTION 'invalid_outbox_receipt';END IF;UPDATE public.notification_outbox SET state='sent',sent_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=a_id AND state='sending' AND attempt_token=a_token;RETURN FOUND;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_outbox_retry_pre_submit(a_id bigint,a_token text,a_evidence_sha256 text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_id IS NULL OR a_id<=0 OR a_token IS NULL OR length(a_token)<>32 OR a_evidence_sha256 IS NULL OR a_evidence_sha256 !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid_pre_submit_evidence';END IF;UPDATE public.notification_outbox SET state='pending',claimed_at=NULL,attempt_token=NULL,updated_at=clock_timestamp(),review_reason='NOT_ATTEMPTED:'||a_evidence_sha256 WHERE id=a_id AND state='sending' AND attempt_token=a_token;RETURN FOUND;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_outbox_mark_uncertain(a_id bigint,a_token text,a_reason text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN a_reason=trim(a_reason);IF a_id IS NULL OR a_id<=0 OR a_token IS NULL OR length(a_token)<>32 OR a_reason IS NULL OR length(a_reason)<1 OR length(a_reason)>200 THEN RAISE EXCEPTION 'invalid_uncertain_outcome';END IF;UPDATE public.notification_outbox SET state='review',review_reason=a_reason,updated_at=clock_timestamp() WHERE id=a_id AND state='sending' AND attempt_token=a_token;RETURN FOUND;END $$;
ALTER FUNCTION public.bot_b5_outbox_claim() OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_outbox_mark_sent(bigint,text) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_outbox_retry_pre_submit(bigint,text,text) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_outbox_mark_uncertain(bigint,text,text) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b5_outbox_claim(),public.bot_b5_outbox_mark_sent(bigint,text),public.bot_b5_outbox_retry_pre_submit(bigint,text,text),public.bot_b5_outbox_mark_uncertain(bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b5_outbox_claim(),public.bot_b5_outbox_mark_sent(bigint,text),public.bot_b5_outbox_retry_pre_submit(bigint,text,text),public.bot_b5_outbox_mark_uncertain(bigint,text,text) TO obsidian_exchange_bot;
