-- E0.3 PROPOSAL ONLY. Pending-only claim and evidence-bound pre-submit release.
CREATE UNIQUE INDEX IF NOT EXISTS uq_sell_deposit_tx ON public.sell_orders(currency,tx_hash) WHERE tx_hash IS NOT NULL AND tx_hash<>'';
CREATE TABLE public.sell_payout_attempts(id bigserial PRIMARY KEY,sell_id bigint NOT NULL,attempt_token text NOT NULL UNIQUE,state text NOT NULL CHECK(state IN('NOT_STARTED','SUBMITTED','UNKNOWN','CONFIRMED','RELEASED')),evidence_sha256 text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(sell_id,attempt_token));
GRANT SELECT(id,user_id,rub_amount,status,tx_hash,payout_ref),UPDATE(status,updated_at) ON public.sell_orders TO obsidian_exchange_bot_owner;
GRANT SELECT(id,sell_id,attempt_token,state),INSERT(sell_id,attempt_token,state),UPDATE(state,evidence_sha256,updated_at) ON public.sell_payout_attempts TO obsidian_exchange_bot_owner;
GRANT USAGE ON SEQUENCE public.sell_payout_attempts_id_seq TO obsidian_exchange_bot_owner;
CREATE OR REPLACE FUNCTION public.bot_b5_sell_claim(a_sell_id bigint) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE s record;t text;BEGIN IF a_sell_id IS NULL OR a_sell_id<=0 THEN RAISE EXCEPTION 'invalid_sell_id';END IF;SELECT id,user_id,rub_amount,status,tx_hash INTO s FROM public.sell_orders WHERE id=a_sell_id FOR UPDATE;IF NOT FOUND THEN RETURN NULL;END IF;IF s.status<>'pending' OR s.tx_hash IS NULL OR length(trim(s.tx_hash))<1 THEN RETURN jsonb_build_object('claimed',false,'status',s.status);END IF;t=md5(random()::text||clock_timestamp()::text||a_sell_id::text);UPDATE public.sell_orders SET status='paying',updated_at=clock_timestamp() WHERE id=a_sell_id AND status='pending';IF NOT FOUND THEN RETURN jsonb_build_object('claimed',false,'status',s.status);END IF;INSERT INTO public.sell_payout_attempts(sell_id,attempt_token,state) VALUES(a_sell_id,t,'NOT_STARTED');RETURN jsonb_build_object('claimed',true,'user_id',s.user_id,'rub_amount',s.rub_amount,'status','paying','attempt_token',t);END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_sell_reject(a_sell_id bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_sell_id IS NULL OR a_sell_id<=0 THEN RAISE EXCEPTION 'invalid_sell_id';END IF;UPDATE public.sell_orders SET status='rejected',updated_at=clock_timestamp() WHERE id=a_sell_id AND status='pending';RETURN FOUND;END $$;
CREATE OR REPLACE FUNCTION public.bot_b5_sell_release_pre_submit(a_sell_id bigint,a_token text,a_evidence_sha256 text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN IF a_sell_id IS NULL OR a_sell_id<=0 OR a_token IS NULL OR length(a_token)<>32 OR a_evidence_sha256 IS NULL OR a_evidence_sha256 !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid_release_evidence';END IF;PERFORM 1 FROM public.sell_orders WHERE id=a_sell_id AND status='paying' AND coalesce(payout_ref,'')='' FOR UPDATE;IF NOT FOUND THEN RETURN false;END IF;UPDATE public.sell_payout_attempts SET state='RELEASED',evidence_sha256=a_evidence_sha256,updated_at=clock_timestamp() WHERE sell_id=a_sell_id AND attempt_token=a_token AND state='NOT_STARTED';IF NOT FOUND THEN RETURN false;END IF;UPDATE public.sell_orders SET status='pending',updated_at=clock_timestamp() WHERE id=a_sell_id AND status='paying' AND coalesce(payout_ref,'')='';IF NOT FOUND THEN RAISE EXCEPTION 'sell_release_lost';END IF;RETURN true;END $$;
ALTER FUNCTION public.bot_b5_sell_claim(bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_sell_reject(bigint) OWNER TO obsidian_exchange_bot_owner;ALTER FUNCTION public.bot_b5_sell_release_pre_submit(bigint,text,text) OWNER TO obsidian_exchange_bot_owner;
REVOKE ALL ON FUNCTION public.bot_b5_sell_claim(bigint),public.bot_b5_sell_reject(bigint),public.bot_b5_sell_release_pre_submit(bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_b5_sell_claim(bigint),public.bot_b5_sell_reject(bigint),public.bot_b5_sell_release_pre_submit(bigint,text,text) TO obsidian_exchange_bot;
